### ISSUE TITLE
Add Token ART-Token

### ISSUE THREAD

**Issue by chy2021** [Koichi-Swap/koichi-swap-tokenlists#13]
1029
cfx:achgfs1uu8drfvy8ju05grkwgct9pfdckym9pc15dc
![artt16](https://user-images.githubusercontent.com/1519538/143193981-a7111ce9-1bd0-4454-8957-f111586d48a4.png)

**Comment by NucleonProtocol** [comment]
{
    "chainId": 1029,
    "address": "cfx:achgfs1uu8drfvy8ju05grkwgct9pfdckym9pc15dc",
    "name": "Art Token",
    "symbol": "ARTT",
    "decimals": 18,
    "logoURI": "https://user-images.githubusercontent.com/57596004/143400967-23530edb-ae70-491d-b27b-7a123fc84a82.png"
}

**Comment by KoichiSwap** [comment]
> { "chainId": 1029, "address": "cfx:achgfs1uu8drfvy8ju05grkwgct9pfdckym9pc15dc", "name": "Art Token", "symbol": "ARTT", "decimals": 18, "logoURI": "https://scan-icons.oss-cn-hongkong.aliyuncs.com/mainnet/cfx%3Aachgfs1uu8drfvy8ju05grkwgct9pfdckym9pc15dc.icon" }

please provide png format token

**Comment by article-i** [comment]
![Artii](https://user-images.githubusercontent.com/57596004/143398290-80fc921b-9740-45dc-b650-c74c9c25e1c2.png)

**Comment by NucleonProtocol** [comment]
![ARTT_small](https://user-images.githubusercontent.com/57596004/143400967-23530edb-ae70-491d-b27b-7a123fc84a82.png)

**Comment by KoichiSwap** [comment]
Please add liquidity in Koichi Swap first, then we will add the token to tokenlist.
