### ISSUE TITLE
ADD Token DAN

### ISSUE THREAD

**Issue by chy2021** [Koichi-Swap/koichi-swap-tokenlists#4]
Chain ID: 1029
Token address: cfx:acbyzcbfpymaz43rr6s1gtx0fb08guj88uzc05rch
Logo:
![dan](https://user-images.githubusercontent.com/1519538/143191917-0036b0f0-8043-4d25-8609-a94ea737f41d.png)

**Comment by KoichiSwap** [comment]
already in token lists.
