### ISSUE TITLE
Add Token Luminos

### ISSUE THREAD

**Issue by chy2021** [Koichi-Swap/koichi-swap-tokenlists#5]
Chain ID: 1029
Token address: cfx:acbk7ugzw24jrjct9p4yz571x4e0agcffjzdkphen6
Logo:
![lumi](https://user-images.githubusercontent.com/1519538/143192458-bbd8a577-4adb-44a1-bc0b-fcecac2b0000.png)

**Comment by KoichiSwap** [comment]
already in token lists.
