### ISSUE TITLE
add Token YAO

### ISSUE THREAD

**Issue by chy2021** [Koichi-Swap/koichi-swap-tokenlists#6]
Chain ID： 1029
Token address： cfx:acaucwuza1nm7wfj1bwkjttz7b0eh4ak7ur7fue1dy
Token logo：
![yao200](https://user-images.githubusercontent.com/1519538/143192906-f42a2e40-eaa7-454b-b690-e96135425b10.png)

**Comment by KoichiSwap** [comment]
already in token lists.
