### ISSUE TITLE
Add Token TREA

### ISSUE THREAD

**Issue by chy2021** [Koichi-Swap/koichi-swap-tokenlists#7]
Chain ID:1029
Token address: cfx:acb9wkgbefcja9rkpds5ve4cm5643jmebae7xjzz8f
Token logo:

![trea32](https://user-images.githubusercontent.com/1519538/143193036-9efd7409-22fa-4474-a00c-6af1f58441b7.png)

**Comment by KoichiSwap** [comment]
already in token lists.
